### ISSUE TITLE
Cursor isn't working on slider

### ISSUE THREAD

**Issue by shahmedme** [codeninjadevs/beats#1]

**Comment by ashimbhowmik** [comment]
I want to solve this issue.

**Comment by srijonashraf** [comment]
It's already working from my end, no changes needed IG!
![ss](https://github.com/codeninjadevs/beats/assets/72869452/14bbf1b6-0f7f-49e9-91b3-8dc1b7574c98)

**Comment by shahmedme** [comment]
Yeah right. I found the issue, It was my device specific. My device cursor wasn't changing. Now it's ok.
