### ISSUE TITLE
Add toggle switch for light/dark mode

### ISSUE THREAD

**Issue by shahmedme** [codeninjadevs/beats#11]
<img width="200" alt="image" src="https://github.com/codeninjadevs/beats/assets/24731446/187c7d8e-c132-40ba-b643-6aafa084a52a">

**Comment by ashimbhowmik** [comment]
I want to do this

**Comment by shahmedme** [comment]
Assigned to you @ashimbhowmik. Please try to use Switch component Ant Design library. https://ant.design/components/switch/
